# -*- coding: utf-8 -*-
"""fiesta astrom3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12E6mCAj-ky2CRndZ5Yq9KHIe8oI6BTlm
"""

!pip install -q fiestaEM corner pandas

import os
os.environ["JAX_PLATFORMS"] = "cpu"
os.environ["CUDA_VISIBLE_DEVICES"] = ""


import jax
print(jax.devices())

import os
os.environ["JAX_PLATFORMS"] = "cpu"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

import jax
jax.config.update("jax_platforms", "cpu")

import fiesta
from fiesta.surrogates import download_recommended_surrogates, print_built_in_surrogates
from fiesta.inference.lightcurve_model import FluxModel

print("OK")

import jax
import jaxlib
import fiesta
import numpy as np

print("jax:", jax.__version__)
print("jaxlib:", jaxlib.__version__)
print("numpy:", np.__version__)
print("fiesta imported OK")

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

plt.rcParams["text.usetex"] = False
plt.rcParams["mathtext.fontset"] = "dejavusans"


import os, sys, warnings, zipfile
import numpy as np
import pandas as pd
import corner
import fiesta
from fiesta.surrogates import download_recommended_surrogates
from fiesta.inference.lightcurve_model import FluxModel

warnings.filterwarnings("ignore")
rng = np.random.default_rng(42)


download_recommended_surrogates()

kn_dir = os.path.join(os.path.dirname(fiesta.__file__), "surrogates", "KN")
kn_names = sorted(os.listdir(kn_dir)) if os.path.exists(kn_dir) else []
print("Available KN surrogates:", kn_names)

surrogate_name = kn_names[0]
print(f"Using surrogate: {surrogate_name}")

filters = ["lsstu", "lsstg", "lsstr", "lssti", "lsstz", "lssty"]


try:
    _test_model = FluxModel(name=surrogate_name, filters=filters)
    _test_params = {}
    for p in _test_model.parameter_names:
        dist_info = _test_model.parameter_distributions[p]
        if isinstance(dist_info, tuple) and len(dist_info) >= 2:
            _test_params[p] = float((dist_info[0] + dist_info[1]) / 2.0)
        else:
            _test_params[p] = 0.0
    _test_params.setdefault("redshift", 0.01)
    _test_params.setdefault("luminosity_distance", 40.0)
    _t_test, _mags_test = _test_model.predict(_test_params)
    missing = [f for f in filters if f not in _mags_test]
    if missing:
        raise ValueError(f"Surrogate missing filters: {missing}")
    print(f"Filter check passed — '{surrogate_name}' supports: {filters}")
except Exception as e:
    raise RuntimeError(f"Filter validation failed: {e}") from e

model = FluxModel(name=surrogate_name, filters=filters)
print("Parameter names:", model.parameter_names)
print("Parameter distributions:", model.parameter_distributions)

parameter_names = list(model.parameter_names)
bounds = {}
for p in parameter_names:
    dist_info = model.parameter_distributions[p]
    if isinstance(dist_info, tuple) and len(dist_info) >= 2:
        bounds[p] = [float(dist_info[0]), float(dist_info[1])]
    else:
        bounds[p] = [0.0, 1.0]
print("Surrogate training bounds:", bounds)

n_samples   = 2000
REDSHIFT    = 0.0079
DISTANCE    = 40.0   # Mpc

training_params = np.column_stack([
    rng.uniform(*bounds.get(p, [0.0, 1.0]), n_samples) for p in parameter_names
])

all_mags   = {f: [] for f in filters}
peak_props = []
times      = None
failed     = []

for idx, row in enumerate(training_params):
    params = dict(zip(parameter_names, row))
    params.setdefault("redshift", REDSHIFT)
    params.setdefault("luminosity_distance", DISTANCE)
    try:
        t, mags = model.predict(params)
        if times is None:
            times = t
        for f in filters:
            all_mags[f].append(np.asarray(mags[f]))

        brightest = np.asarray(mags[filters[2]])   # r-band
        valid = np.isfinite(brightest)
        if valid.any():
            peak_idx    = np.argmin(brightest[valid])
            peak_mag    = brightest[valid][peak_idx]
            peak_time   = t[valid][peak_idx]
            decline_mask = t[valid] >= peak_time
            rise_time    = peak_time - t[valid][0]
            decline_rate = (
                (brightest[valid][decline_mask][-1] - peak_mag) /
                (t[valid][decline_mask][-1] - peak_time + 1e-9)
                if decline_mask.sum() > 1 else np.nan
            )
        else:
            peak_mag = peak_time = rise_time = decline_rate = np.nan

        peak_props.append({"peak_mag_r": peak_mag, "time_of_peak_r": peak_time,
                           "rise_time_r": rise_time, "decline_rate_r": decline_rate})
    except Exception as e:
        failed.append((idx, str(e)))
        placeholder = np.full(len(times) if times is not None else 1, np.nan)
        for f in filters:
            all_mags[f].append(placeholder.copy())
        peak_props.append({"peak_mag_r": np.nan, "time_of_peak_r": np.nan,
                           "rise_time_r": np.nan, "decline_rate_r": np.nan})

print(f"Failed samples: {len(failed)} / {n_samples}")
if failed:
    print("First few failures:", failed[:5])

for f in filters:
    all_mags[f] = np.array(all_mags[f])


np.save("fiesta_lightcurves.npy", np.stack([all_mags[f] for f in filters], axis=1))
np.save("fiesta_times.npy", times)

param_df = pd.DataFrame(training_params, columns=parameter_names)
param_df["redshift"]            = REDSHIFT
param_df["luminosity_distance"] = DISTANCE
peak_df  = pd.DataFrame(peak_props)
param_df = pd.concat([param_df, peak_df], axis=1)
param_df.to_csv("fiesta_parameters.csv", index=False)

meta = {
    "surrogate": surrogate_name, "n_samples": n_samples,
    "filters": str(filters), "redshift": REDSHIFT,
    "luminosity_distance_Mpc": DISTANCE,
    "n_times": len(times),
    "time_min_days": float(times.min()),
    "time_max_days": float(times.max()),
    "n_failed": len(failed),
}
pd.DataFrame([meta]).to_csv("fiesta_metadata.csv", index=False)
print("Saved: fiesta_lightcurves.npy, fiesta_times.npy, fiesta_parameters.csv, fiesta_metadata.csv")


base_params = {p: (bounds[p][0] + bounds[p][1]) / 2.0 for p in parameter_names}
base_params.setdefault("redshift", REDSHIFT)
base_params.setdefault("luminosity_distance", DISTANCE)


fig, axes = plt.subplots(2, 3, figsize=(16, 8))
axes = axes.flatten()
for ax, f in zip(axes, filters):
    vc = all_mags[f][np.all(np.isfinite(all_mags[f]), axis=1)]
    median = np.nanmedian(vc, axis=0)
    p16    = np.nanpercentile(vc, 16, axis=0)
    p84    = np.nanpercentile(vc, 84, axis=0)
    ax.fill_between(times, p16, p84, alpha=0.3, color="steelblue", label="16-84%")
    ax.plot(times, median, color="steelblue", lw=2, label="Median")
    for i in range(min(30, len(vc))):
        ax.plot(times, vc[i], alpha=0.08, lw=0.6, color="steelblue")
    ax.invert_yaxis()
    ax.set_xlabel("Time (days)")
    ax.set_ylabel("Magnitude")
    ax.set_title(f"Filter: {f}")
    ax.legend(fontsize=8)
plt.suptitle(f"Kilonova Population - {surrogate_name} ({n_samples} samples)", fontsize=13)
plt.tight_layout()
plt.savefig("population_lightcurves.png", dpi=150, bbox_inches="tight")
plt.close()
print("Saved population_lightcurves.png")

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
color_pairs  = [("lsstg", "lsstr"), ("lsstr", "lssti"), ("lssti", "lsstz")]
pair_labels  = ["g-r", "r-i", "i-z"]
for ax, (f1, f2), label in zip(axes, color_pairs, pair_labels):
    for i in range(min(50, n_samples)):
        c = all_mags[f1][i] - all_mags[f2][i]
        if np.all(np.isfinite(c)):
            ax.plot(times, c, alpha=0.15, lw=0.8, color="darkorange")
    ax.plot(times, np.nanmedian(all_mags[f1] - all_mags[f2], axis=0),
            color="darkorange", lw=2)
    ax.axhline(0, color="gray", ls="--", lw=0.8)
    ax.set_xlabel("Time (days)")
    ax.set_ylabel(f"{label} (mag)")
    ax.set_title(f"Color Evolution: {label}")
plt.suptitle("Kilonova Color Evolution", fontsize=13)
plt.tight_layout()
plt.savefig("color_evolution.png", dpi=150, bbox_inches="tight")
plt.close()
print("Saved color_evolution.png")


theta_param = next(
    (p for p in parameter_names if "theta" in p.lower() or "inclination" in p.lower()),
    None,
)
if theta_param:
    theta_lo, theta_hi = bounds[theta_param]
    theta_values = np.linspace(theta_lo, theta_hi, 4)
    theta_labels = [f"{np.degrees(v):.0f} deg" for v in theta_values]
    fig, axes = plt.subplots(1, len(filters), figsize=(18, 4))
    colors = ["navy", "steelblue", "tomato", "firebrick"]
    for color, theta, lbl in zip(colors, theta_values, theta_labels):
        p = dict(base_params)
        p[theta_param] = theta
        try:
            t, mags = model.predict(p)
            for ax, f in zip(axes, filters):
                ax.plot(t, np.asarray(mags[f]), color=color, lw=1.8, label=lbl)
        except Exception as e:
            print(f"Angle {lbl} failed: {e}")
    for ax, f in zip(axes, filters):
        ax.invert_yaxis()
        ax.set_xlabel("Time (days)")
        ax.set_ylabel("Magnitude")
        ax.set_title(f"Filter: {f}")
        ax.legend(title=theta_param, fontsize=8)
    plt.suptitle("Viewing-Angle Study", fontsize=13)
    plt.tight_layout()
    plt.savefig("viewing_angle_study.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("Saved viewing_angle_study.png")
else:
    print("No inclination/theta parameter found; skipping viewing-angle plot.")


mej_dyn_param  = next((p for p in parameter_names if "mej_dyn"  in p.lower()), None)
mej_wind_param = next((p for p in parameter_names if "mej_wind" in p.lower()), None)

if mej_dyn_param and mej_wind_param:
    lo_d, hi_d = bounds[mej_dyn_param]
    mej_grid   = np.linspace(lo_d, hi_d, 4)
    fig, axes  = plt.subplots(1, len(filters), figsize=(18, 4))
    colors     = ["navy", "steelblue", "tomato", "firebrick"]
    for color, mej_val in zip(colors, mej_grid):
        p = dict(base_params)
        p[mej_dyn_param]  = mej_val
        p[mej_wind_param] = mej_val
        try:
            t, mags = model.predict(p)
            label = f"log10 mej={mej_val:.2f}"
            for ax, f in zip(axes, filters):
                ax.plot(t, np.asarray(mags[f]), color=color, lw=1.8, label=label)
        except Exception as e:
            print(f"Ejecta mass {mej_val:.2f} failed: {e}")
    for ax, f in zip(axes, filters):
        ax.invert_yaxis()
        ax.set_xlabel("Time (days)")
        ax.set_ylabel("Magnitude")
        ax.set_title(f"Filter: {f}")
        ax.legend(fontsize=7)
    plt.suptitle("Ejecta-Mass Study", fontsize=13)
    plt.tight_layout()
    plt.savefig("ejecta_mass_study.png", dpi=150, bbox_inches="tight")
    plt.close()
    print("Saved ejecta_mass_study.png")
else:
    print("No mej_dyn/mej_wind parameters found; skipping ejecta-mass plot.")

dist_values = [40.0, 100.0, 200.0, 400.0]
dist_param  = next((p for p in parameter_names if "distance" in p.lower()), None)
fig, axes   = plt.subplots(1, len(filters), figsize=(18, 4))
colors      = ["navy", "steelblue", "tomato", "firebrick"]
for color, d in zip(colors, dist_values):
    p = dict(base_params)
    if dist_param:
        p[dist_param] = d
    p["luminosity_distance"] = d
    try:
        t, mags = model.predict(p)
        for ax, f in zip(axes, filters):
            ax.plot(t, np.asarray(mags[f]), color=color, lw=1.8, label=f"{d} Mpc")
    except Exception as e:
        print(f"Distance {d} Mpc failed: {e}")
for ax, f in zip(axes, filters):
    ax.invert_yaxis()
    ax.set_xlabel("Time (days)")
    ax.set_ylabel("Magnitude")
    ax.set_title(f"Filter: {f}")
    ax.legend(fontsize=8)
plt.suptitle("Distance Study", fontsize=13)
plt.tight_layout()
plt.savefig("distance_study.png", dpi=150, bbox_inches="tight")
plt.close()
print("Saved distance_study.png")


corner_params = [p for p in parameter_names if p in bounds]
corner_data   = param_df[corner_params].dropna().values
fig = corner.corner(
    corner_data,
    labels=corner_params,
    quantiles=[0.16, 0.5, 0.84],
    show_titles=True,
    title_kwargs={"fontsize": 9},
    color="steelblue",
)
fig.suptitle("Kilonova Parameter Space", y=1.01, fontsize=13)
plt.savefig("corner_plot.png", dpi=150, bbox_inches="tight")
plt.close()
print("Saved corner_plot.png")

outputs = [
    "fiesta_lightcurves.npy",
    "fiesta_times.npy",
    "fiesta_parameters.csv",
    "fiesta_metadata.csv",
    "population_lightcurves.png",
    "color_evolution.png",
    "viewing_angle_study.png",
    "ejecta_mass_study.png",
    "distance_study.png",
    "corner_plot.png",
]

with zipfile.ZipFile("fiesta_outputs.zip", "w", zipfile.ZIP_DEFLATED) as zf:
    for fname in outputs:
        if os.path.exists(fname):
            zf.write(fname)
            print(f"  + {fname}")
        else:
            print(f"  MISSING (skipped): {fname}")

print("\nAll done!")
print(f"Dataset summary: {n_samples} samples | {len(filters)} filters | {len(times)} time steps")
print(f"Failed: {len(failed)}")
print("\nAstroM3 pipeline ready:")
print("  fiesta_lightcurves.npy  -> shape (N, n_filters, n_times)")
print("  fiesta_parameters.csv   -> ground truth labels")
print("  fiesta_metadata.csv     -> dataset provenance")

